# Generated by Django 4.0.4 on 2022-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeCatPais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('descri_largo_pais', models.CharField(blank=True, max_length=50, null=True)),
                ('descri_corto_pais', models.CharField(blank=True, max_length=10, null=True)),
                ('estatus_pais', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
