# Generated by Django 4.0.3 on 2022-06-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEscolar', '0002_alter_secatpais_estatus_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secatpais',
            options={'managed': False},
        ),
    ]
