# Generated by Django 4.0.3 on 2022-06-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEscolar', '0003_alter_secatpais_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secatpais',
            table='se_cat_pais',
        ),
    ]
