# Generated by Django 4.0.3 on 2022-06-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlEscolar', '0006_controlescolarsecatpais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlescolarSecatpais',
        ),
        migrations.DeleteModel(
            name='EstadosEstado',
        ),
        migrations.DeleteModel(
            name='EstadosPais',
        ),
    ]
