# Generated by Django 4.0.4 on 2022-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEscolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secatpais',
            name='estatus_pais',
            field=models.CharField(blank=True, default='A', max_length=1, null=True),
        ),
    ]
