# Generated by Django 4.0.3 on 2022-06-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlEscolar', '0005_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlescolarSecatpais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('descri_largo_pais', models.CharField(blank=True, max_length=50, null=True)),
                ('descri_corto_pais', models.CharField(blank=True, max_length=10, null=True)),
                ('estatus_pais', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'controlEscolar_secatpais',
                'managed': False,
            },
        ),
    ]
